openapi: '3.0.2'
info:
  title: API для тестового проекта проката автомобилей
  version: '1.0'
servers:
  - url: http://carsharing.kolei.ru
tags:
  - name: auth
    description: Регистрация и авторизация (получение токена)
paths:
  /register:
    post:
      tags:
        - auth
      summary: Регистрация нового пользователя в системе
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email пользователя. Email должен соответствовать паттерну "name@domenname.ru", где имя и домен второго уровня могут состоять только из маленьких букв и цифр, домен верхнего уровня - только из маленьких букв. Длина домена верхнего уровня - не более 3х символов.
                  example: kolei@yandex.ru
                password:
                  type: string
                  description: Пароль
                  example: qwerty
                firstName:
                  type: string
                  description: Имя пользователя
                  example: Евгений
                lastName:
                  type: string
                  description: Фамилия пользователя
                  example: Колесников
              required:
                - email
                - password
                - firstName
                - lastName
      responses:
        '200':
          description: OK
